name: ChestExporter
version: '1.0-SNAPSHOT'
main: org.zephbyte.chestExporter.ChestExporter
api-version: '1.21'
commands:
  chestexporter:
    description: Exports the contents of a chest to a /setblock command.
    usage: /chestexporter <export|reload>
    aliases: [exportchest, ce]
permissions:
  chestexporter.use:
    description: Allows players to use the /chestexporter export command.
    default: op
  chestexporter.reload:
    description: Allows players to use the /chestexporter reload command.
    default: op
